### ISSUE TITLE
Hi, it would be nice to have both monodevelop and emgu-cv in a single docker

### ISSUE THREAD

**Issue by cmencar** [zachdeibert/docker-images#1]

**Comment by zachdeibert** [comment]
Is it possible to install it through NuGet for your project?

**Comment by cmencar** [comment]
Sorry, I could not help you. I'm quite new to these technologies.

**Comment by zachdeibert** [comment]
I cannot get Emgu CV to work on Debian right now, and my docker images are all based on a Debian base image.  Also, this is more of a specific dependency that should be installed using NuGet (https://www.nuget.org/) or a similar solution.
